-- 新增学校学院数据插入SQL文件
-- 包含拉夫堡大学(ID: 42)、萨里大学(ID: 37)、哈德斯菲尔德大学(ID: 48)的学院数据

-- 开始事务
BEGIN;

-- 拉夫堡大学 (ID: 42) 学院数据
INSERT INTO school_faculties (
    name, english_name, school_id, code, description, history, ranking,
    dean_name, faculty_count, student_count, website, image_url,
    featured_programs, research_areas, contact_email, contact_phone,
    created_time, updated_time, is_deleted, status
) VALUES 
('传播与媒体系', 'School of Communication and Media', 42, 'SCM', '在传播学和媒体研究方面提供专业教育', '成立于1960年代，在媒体传播和数字媒体方面享有声誉', 1, 'Prof. Sarah Johnson', 85, 1800, 'https://www.lboro.ac.uk/media', '/images/schools/loughborough-media.jpg', '传播学,媒体研究,数字媒体', '媒体传播,数字技术,社交媒体', 'media@lboro.ac.uk', '+44 1509 222581', NOW(), NOW(), 0, 1),
('体育、运动和健康科学系', 'School of Sport, Exercise and Health Sciences', 42, 'SSEHS', '世界领先的体育科学教育和研究机构', '成立于1909年，在体育科学和运动医学方面享有国际声誉', 2, 'Prof. Michael Brown', 120, 2200, 'https://www.lboro.ac.uk/sport', '/images/schools/loughborough-sport.jpg', '体育科学,运动医学,健康科学', '运动生理学,体育心理学,运动康复', 'sport@lboro.ac.uk', '+44 1509 222582', NOW(), NOW(), 0, 1),
('体育事业研究所', 'Institute for Sport Business', 42, 'ISB', '专注于体育商业和管理的专业研究机构', '建立于2000年代，在体育产业管理方面领先', 3, 'Prof. David Wilson', 45, 600, 'https://www.lboro.ac.uk/sport-business', '/images/schools/loughborough-sport-business.jpg', '体育管理,体育营销,体育经济', '体育产业,体育商业,体育政策', 'sportbusiness@lboro.ac.uk', '+44 1509 222583', NOW(), NOW(), 0, 1),
('创意未来研究所', 'Institute for Creative Futures', 42, 'ICF', '专注于创意产业和未来技术的研究机构', '成立于2010年代，在创意技术和数字创新方面领先', 4, 'Prof. Lisa Anderson', 60, 800, 'https://www.lboro.ac.uk/creative-futures', '/images/schools/loughborough-creative.jpg', '创意技术,数字艺术,创新设计', '创意产业,数字创新,未来技术', 'creative@lboro.ac.uk', '+44 1509 222584', NOW(), NOW(), 0, 1),
('创意艺术系', 'School of Creative Arts', 42, 'SCA', '在艺术设计和创意实践方面提供专业教育', '历史悠久，在艺术教育和设计实践方面享有声誉', 5, 'Prof. Emma Roberts', 70, 1200, 'https://www.lboro.ac.uk/arts', '/images/schools/loughborough-arts.jpg', '艺术设计,创意实践,视觉艺术', '当代艺术,设计创新,艺术理论', 'arts@lboro.ac.uk', '+44 1509 222585', NOW(), NOW(), 0, 1),
('创新和企业家精神研究所', 'Institute for Innovation and Entrepreneurship', 42, 'IIE', '专注于创新管理和企业家精神的研究机构', '建立于2000年代，在创新研究和创业教育方面领先', 6, 'Prof. James Miller', 55, 700, 'https://www.lboro.ac.uk/innovation', '/images/schools/loughborough-innovation.jpg', '创新管理,企业家精神,商业创新', '创新研究,创业教育,技术转移', 'innovation@lboro.ac.uk', '+44 1509 222586', NOW(), NOW(), 0, 1),
('化学工程系', 'Department of Chemical Engineering', 42, 'DCE', '在化学工程和工艺技术方面提供专业教育', '成立于1960年代，在化学工程和材料科学方面享有声誉', 7, 'Prof. Catherine White', 65, 900, 'https://www.lboro.ac.uk/chemical-engineering', '/images/schools/loughborough-chemical.jpg', '化学工程,工艺技术,材料科学', '化学工艺,材料研究,环境工程', 'chemical@lboro.ac.uk', '+44 1509 222587', NOW(), NOW(), 0, 1),
('化学系', 'Department of Chemistry', 42, 'DC', '在化学科学和分析化学方面提供专业教育', '历史悠久，在化学研究和分析技术方面领先', 8, 'Prof. Andrew Johnson', 75, 1100, 'https://www.lboro.ac.uk/chemistry', '/images/schools/loughborough-chemistry.jpg', '化学,分析化学,有机化学', '化学合成,分析技术,材料化学', 'chemistry@lboro.ac.uk', '+44 1509 222588', NOW(), NOW(), 0, 1),
('国际关系、政治和历史系', 'Department of International Relations, Politics and History', 42, 'DIRPH', '在国际关系和政治学方面提供专业教育', '成立于1960年代，在国际关系和政治理论方面享有声誉', 9, 'Prof. Helen Davis', 80, 1300, 'https://www.lboro.ac.uk/politics', '/images/schools/loughborough-politics.jpg', '国际关系,政治学,历史学', '国际政治,政治理论,历史研究', 'politics@lboro.ac.uk', '+44 1509 222589', NOW(), NOW(), 0, 1),
('国际管理与创业系', 'School of International Management and Entrepreneurship', 42, 'SIME', '在国际商务和创业管理方面提供专业教育', '建立于1990年代，在国际商务和创业教育方面领先', 10, 'Prof. Mark Thompson', 90, 1600, 'https://www.lboro.ac.uk/management', '/images/schools/loughborough-management.jpg', '国际商务,创业管理,战略管理', '国际贸易,创业研究,商业战略', 'management@lboro.ac.uk', '+44 1509 222590', NOW(), NOW(), 0, 1),
('地理与环境系', 'Department of Geography and Environment', 42, 'DGE', '在地理学和环境科学方面提供专业教育', '成立于1960年代，在环境研究和地理信息系统方面领先', 11, 'Prof. Robert Chen', 70, 1000, 'https://www.lboro.ac.uk/geography', '/images/schools/loughborough-geography.jpg', '地理学,环境科学,地理信息系统', '环境研究,气候变化,空间分析', 'geography@lboro.ac.uk', '+44 1509 222591', NOW(), NOW(), 0, 1),
('外交与国际事务系', 'Department of Diplomacy and International Affairs', 42, 'DDIA', '在外交学和国际事务方面提供专业教育', '建立于2000年代，在外交研究和国际关系方面享有声誉', 12, 'Prof. Susan Wilson', 50, 650, 'https://www.lboro.ac.uk/diplomacy', '/images/schools/loughborough-diplomacy.jpg', '外交学,国际事务,国际法', '外交研究,国际组织,全球治理', 'diplomacy@lboro.ac.uk', '+44 1509 222592', NOW(), NOW(), 0, 1),
('媒体和创意产业研究所', 'Institute for Media and Creative Industries', 42, 'IMCI', '专注于媒体产业和创意经济的研究机构', '成立于2010年代，在媒体产业研究方面领先', 13, 'Prof. David Anderson', 40, 500, 'https://www.lboro.ac.uk/media-industries', '/images/schools/loughborough-media-industries.jpg', '媒体产业,创意经济,数字媒体', '媒体研究,创意产业,数字经济', 'mediaindustries@lboro.ac.uk', '+44 1509 222593', NOW(), NOW(), 0, 1),
('建筑学、建筑和土木工程系', 'School of Architecture, Building and Civil Engineering', 42, 'SABCE', '在建筑和土木工程方面提供专业教育', '成立于1960年代，在建筑设计和土木工程方面享有声誉', 14, 'Prof. Lisa Brown', 95, 1400, 'https://www.lboro.ac.uk/architecture', '/images/schools/loughborough-architecture.jpg', '建筑学,土木工程,建筑技术', '可持续建筑,结构工程,建筑设计', 'architecture@lboro.ac.uk', '+44 1509 222594', NOW(), NOW(), 0, 1),
('拉夫堡商学院', 'Loughborough Business School', 42, 'LBS', '提供世界级的商业教育和管理培训', '建立于1960年代，在商业教育和管理研究方面享有国际声誉', 15, 'Prof. Michael Roberts', 110, 2500, 'https://www.lboro.ac.uk/business', '/images/schools/loughborough-business.jpg', '工商管理,金融学,市场营销', '商业战略,金融创新,市场研究', 'business@lboro.ac.uk', '+44 1509 222595', NOW(), NOW(), 0, 1),
('数字技术研究所', 'Institute for Digital Technologies', 42, 'IDT', '专注于数字技术和人工智能的研究机构', '成立于2010年代，在数字技术和AI研究方面领先', 16, 'Prof. Emma Miller', 85, 1100, 'https://www.lboro.ac.uk/digital', '/images/schools/loughborough-digital.jpg', '数字技术,人工智能,数据科学', '机器学习,大数据,数字创新', 'digital@lboro.ac.uk', '+44 1509 222596', NOW(), NOW(), 0, 1),
('数学科学系', 'Department of Mathematical Sciences', 42, 'DMS', '在数学和统计学方面提供专业教育', '历史悠久，在应用数学和统计学方面享有声誉', 17, 'Prof. James White', 60, 800, 'https://www.lboro.ac.uk/mathematics', '/images/schools/loughborough-maths.jpg', '数学,统计学,应用数学', '数学建模,统计分析,计算数学', 'maths@lboro.ac.uk', '+44 1509 222597', NOW(), NOW(), 0, 1),
('机械、电气和制造工程系', 'Department of Mechanical, Electrical and Manufacturing Engineering', 42, 'DMEME', '在工程技术方面提供综合性专业教育', '成立于1960年代，在机械工程和制造技术方面领先', 18, 'Prof. Catherine Johnson', 130, 2000, 'https://www.lboro.ac.uk/engineering', '/images/schools/loughborough-engineering.jpg', '机械工程,电气工程,制造工程', '先进制造,自动化,可再生能源', 'engineering@lboro.ac.uk', '+44 1509 222598', NOW(), NOW(), 0, 1),
('材料系', 'Department of Materials', 42, 'DM', '在材料科学和工程方面提供专业教育', '成立于1960年代，在材料研究和纳米技术方面享有国际声誉', 19, 'Prof. Andrew Davis', 75, 950, 'https://www.lboro.ac.uk/materials', '/images/schools/loughborough-materials.jpg', '材料科学,材料工程,纳米技术', '先进材料,纳米科学,材料表征', 'materials@lboro.ac.uk', '+44 1509 222599', NOW(), NOW(), 0, 1),
('法律系', 'Department of Law', 42, 'DL', '在法学教育和法律研究方面提供专业培训', '建立于1980年代，在商法和体育法方面享有声誉', 20, 'Prof. Helen Thompson', 55, 750, 'https://www.lboro.ac.uk/law', '/images/schools/loughborough-law.jpg', '法学,商法,体育法', '法律研究,商业法律,体育法律', 'law@lboro.ac.uk', '+44 1509 222600', NOW(), NOW(), 0, 1),
('物理系', 'Department of Physics', 42, 'DP', '在物理学和天体物理学方面提供专业教育', '历史悠久，在理论物理和应用物理方面享有声誉', 21, 'Prof. Robert Anderson', 80, 1050, 'https://www.lboro.ac.uk/physics', '/images/schools/loughborough-physics.jpg', '物理学,天体物理学,应用物理', '理论物理,凝聚态物理,光学', 'physics@lboro.ac.uk', '+44 1509 222601', NOW(), NOW(), 0, 1),
('犯罪学、社会学和社会政策系', 'Department of Criminology, Sociology and Social Policy', 42, 'DCSSP', '在社会科学和犯罪学方面提供专业教育', '成立于1970年代，在犯罪学和社会政策研究方面领先', 22, 'Prof. Susan Chen', 65, 900, 'https://www.lboro.ac.uk/criminology', '/images/schools/loughborough-criminology.jpg', '犯罪学,社会学,社会政策', '犯罪研究,社会理论,政策分析', 'criminology@lboro.ac.uk', '+44 1509 222602', NOW(), NOW(), 0, 1),
('航空汽车工程系', 'Department of Aeronautical and Automotive Engineering', 42, 'DAAE', '在航空航天和汽车工程方面提供专业教育', '成立于1960年代，在航空工程和汽车技术方面享有国际声誉', 23, 'Prof. Mark Wilson', 100, 1500, 'https://www.lboro.ac.uk/aeronautical', '/images/schools/loughborough-aeronautical.jpg', '航空工程,汽车工程,交通技术', '航空航天,汽车设计,交通系统', 'aeronautical@lboro.ac.uk', '+44 1509 222603', NOW(), NOW(), 0, 1),
('英语系', 'Department of English', 42, 'DE', '在英语文学和语言学方面提供专业教育', '历史悠久，在英语文学和创意写作方面享有声誉', 24, 'Prof. Emma Davis', 50, 700, 'https://www.lboro.ac.uk/english', '/images/schools/loughborough-english.jpg', '英语文学,语言学,创意写作', '文学研究,语言分析,写作实践', 'english@lboro.ac.uk', '+44 1509 222604', NOW(), NOW(), 0, 1),
('计算机科学系', 'Department of Computer Science', 42, 'DCS', '在计算机科学和信息技术方面提供专业教育', '成立于1970年代，在人工智能和软件工程方面领先', 25, 'Prof. David Miller', 95, 1600, 'https://www.lboro.ac.uk/computer-science', '/images/schools/loughborough-cs.jpg', '计算机科学,软件工程,人工智能', '机器学习,数据科学,网络安全', 'cs@lboro.ac.uk', '+44 1509 222605', NOW(), NOW(), 0, 1),
('设计系', 'School of Design', 42, 'SD', '在设计和创新方面提供专业教育', '成立于1960年代，在工业设计和用户体验设计方面享有国际声誉', 26, 'Prof. Lisa Roberts', 70, 1200, 'https://www.lboro.ac.uk/design', '/images/schools/loughborough-design.jpg', '工业设计,用户体验设计,设计创新', '设计研究,人机交互,产品设计', 'design@lboro.ac.uk', '+44 1509 222606', NOW(), NOW(), 0, 1);

-- 萨里大学 (ID: 37) 学院数据
INSERT INTO school_faculties (
    name, english_name, school_id, code, description, history, ranking,
    dean_name, faculty_count, student_count, website, image_url,
    featured_programs, research_areas, contact_email, contact_phone,
    created_time, updated_time, is_deleted, status
) VALUES 
('化学与化学工程学院', 'School of Chemistry and Chemical Engineering', 37, 'SCCE', '在化学和化学工程方面提供世界级教育', '成立于1960年代，在化学研究和工程应用方面享有国际声誉', 1, 'Prof. Michael Johnson', 95, 1500, 'https://www.surrey.ac.uk/chemistry', '/images/schools/surrey-chemistry.jpg', '化学,化学工程,材料科学', '催化化学,绿色化学,纳米材料', 'chemistry@surrey.ac.uk', '+44 1483 686801', NOW(), NOW(), 0, 1),
('化学与工艺工程系', 'Department of Chemical and Process Engineering', 37, 'DCPE', '在化学工程和工艺技术方面提供专业教育', '建立于1960年代，在化学工程和工艺优化方面领先', 2, 'Prof. Sarah Brown', 70, 1000, 'https://www.surrey.ac.uk/chemical-engineering', '/images/schools/surrey-chemical-eng.jpg', '化学工程,工艺工程,生物工程', '工艺优化,反应工程,分离技术', 'chemeng@surrey.ac.uk', '+44 1483 686802', NOW(), NOW(), 0, 1),
('古尔福德表演学院', 'Guildford School of Acting', 37, 'GSA', '英国顶级的表演艺术学院', '成立于1935年，在戏剧表演和音乐剧方面享有国际声誉', 3, 'Prof. David Wilson', 45, 600, 'https://www.gsauk.org', '/images/schools/surrey-gsa.jpg', '戏剧表演,音乐剧,舞台艺术', '表演艺术,戏剧教育,舞台技术', 'gsa@surrey.ac.uk', '+44 1483 686803', NOW(), NOW(), 0, 1),
('土木与环境工程系', 'Department of Civil and Environmental Engineering', 37, 'DCEE', '在土木工程和环境工程方面提供专业教育', '成立于1960年代，在结构工程和环境技术方面领先', 4, 'Prof. Lisa Anderson', 80, 1200, 'https://www.surrey.ac.uk/civil-engineering', '/images/schools/surrey-civil.jpg', '土木工程,环境工程,结构工程', '可持续工程,水资源管理,结构设计', 'civil@surrey.ac.uk', '+44 1483 686804', NOW(), NOW(), 0, 1),
('心理学学院', 'School of Psychology', 37, 'SP', '在心理学研究和应用方面提供专业教育', '建立于1960年代，在认知心理学和健康心理学方面享有声誉', 5, 'Prof. Emma Roberts', 65, 1100, 'https://www.surrey.ac.uk/psychology', '/images/schools/surrey-psychology.jpg', '心理学,认知科学,健康心理学', '神经心理学,发展心理学,社会心理学', 'psychology@surrey.ac.uk', '+44 1483 686805', NOW(), NOW(), 0, 1),
('政治学系', 'Department of Politics', 37, 'DP', '在政治学和国际关系方面提供专业教育', '成立于1960年代，在政治理论和比较政治方面享有声誉', 6, 'Prof. James Miller', 55, 800, 'https://www.surrey.ac.uk/politics', '/images/schools/surrey-politics.jpg', '政治学,国际关系,公共政策', '政治理论,比较政治,政策分析', 'politics@surrey.ac.uk', '+44 1483 686806', NOW(), NOW(), 0, 1),
('数学系', 'Department of Mathematics', 37, 'DM', '在数学和统计学方面提供专业教育', '历史悠久，在应用数学和数学建模方面享有声誉', 7, 'Prof. Catherine White', 60, 900, 'https://www.surrey.ac.uk/mathematics', '/images/schools/surrey-maths.jpg', '数学,统计学,金融数学', '数学建模,统计分析,计算数学', 'maths@surrey.ac.uk', '+44 1483 686807', NOW(), NOW(), 0, 1),
('文学和语言学院', 'School of Literature and Languages', 37, 'SLL', '在文学和语言学方面提供专业教育', '成立于1960年代，在英语文学和现代语言方面享有声誉', 8, 'Prof. Andrew Johnson', 70, 1000, 'https://www.surrey.ac.uk/literature', '/images/schools/surrey-literature.jpg', '英语文学,现代语言,比较文学', '文学研究,语言学,文化研究', 'literature@surrey.ac.uk', '+44 1483 686808', NOW(), NOW(), 0, 1),
('法学院', 'Surrey Law School', 37, 'SLS', '在法学教育和法律研究方面提供专业培训', '建立于1960年代，在国际法和商法方面享有声誉', 9, 'Prof. Helen Davis', 75, 1300, 'https://www.surrey.ac.uk/law', '/images/schools/surrey-law.jpg', '法学,国际法,商法', '法律研究,人权法,商业法律', 'law@surrey.ac.uk', '+44 1483 686809', NOW(), NOW(), 0, 1),
('物理系', 'Department of Physics', 37, 'DP2', '在物理学和天体物理学方面提供专业教育', '历史悠久，在核物理和量子物理方面享有国际声誉', 10, 'Prof. Robert Chen', 85, 1100, 'https://www.surrey.ac.uk/physics', '/images/schools/surrey-physics.jpg', '物理学,核物理,量子物理', '理论物理,核技术,量子计算', 'physics@surrey.ac.uk', '+44 1483 686810', NOW(), NOW(), 0, 1),
('环境与可持续发展中心', 'Centre for Environment and Sustainability', 37, 'CES', '专注于环境科学和可持续发展的研究中心', '成立于2000年代，在环境研究和可持续发展方面领先', 11, 'Prof. Susan Wilson', 50, 600, 'https://www.surrey.ac.uk/environment', '/images/schools/surrey-environment.jpg', '环境科学,可持续发展,环境管理', '气候变化,环境政策,生态系统', 'environment@surrey.ac.uk', '+44 1483 686811', NOW(), NOW(), 0, 1),
('生物科学和医学学院', 'School of Biosciences and Medicine', 37, 'SBM', '在生物科学和医学方面提供专业教育', '建立于2000年代，在生物医学和分子生物学方面享有声誉', 12, 'Prof. Mark Thompson', 100, 1800, 'https://www.surrey.ac.uk/biosciences', '/images/schools/surrey-biosciences.jpg', '生物科学,医学,生物医学', '分子生物学,细胞生物学,医学研究', 'biosciences@surrey.ac.uk', '+44 1483 686812', NOW(), NOW(), 0, 1),
('电气和电子工程系', 'Department of Electrical and Electronic Engineering', 37, 'DEEE', '在电气工程和电子技术方面提供专业教育', '成立于1960年代，在通信工程和电子系统方面领先', 13, 'Prof. David Anderson', 90, 1400, 'https://www.surrey.ac.uk/electrical-engineering', '/images/schools/surrey-electrical.jpg', '电气工程,电子工程,通信工程', '5G技术,物联网,信号处理', 'electrical@surrey.ac.uk', '+44 1483 686813', NOW(), NOW(), 0, 1),
('社会学系', 'Department of Sociology', 37, 'DS', '在社会学和社会研究方面提供专业教育', '成立于1960年代，在社会理论和社会政策方面享有声誉', 14, 'Prof. Lisa Brown', 55, 750, 'https://www.surrey.ac.uk/sociology', '/images/schools/surrey-sociology.jpg', '社会学,社会研究,社会政策', '社会理论,社会变迁,社会问题', 'sociology@surrey.ac.uk', '+44 1483 686814', NOW(), NOW(), 0, 1),
('经济学院', 'School of Economics', 37, 'SE', '在经济学教育和研究方面提供专业培训', '建立于1960年代，在行为经济学和发展经济学方面享有声誉', 15, 'Prof. Emma Miller', 65, 1000, 'https://www.surrey.ac.uk/economics', '/images/schools/surrey-economics.jpg', '经济学,行为经济学,发展经济学', '经济理论,计量经济学,经济政策', 'economics@surrey.ac.uk', '+44 1483 686815', NOW(), NOW(), 0, 1),
('翻译研究中心', 'Centre for Translation Studies', 37, 'CTS', '专注于翻译学和跨文化交流的研究中心', '成立于1980年代，在翻译研究和口译培训方面享有国际声誉', 16, 'Prof. James White', 40, 500, 'https://www.surrey.ac.uk/translation', '/images/schools/surrey-translation.jpg', '翻译学,口译,跨文化交流', '翻译理论,口译技术,语言服务', 'translation@surrey.ac.uk', '+44 1483 686816', NOW(), NOW(), 0, 1),
('萨里商学院', 'Surrey Business School', 37, 'SBS', '提供世界级的商业教育和管理培训', '建立于1960年代，在国际商务和创业管理方面享有声誉', 17, 'Prof. Catherine Johnson', 120, 2500, 'https://www.surrey.ac.uk/business', '/images/schools/surrey-business.jpg', '工商管理,国际商务,创业管理', '商业战略,国际贸易,创新管理', 'business@surrey.ac.uk', '+44 1483 686817', NOW(), NOW(), 0, 1),
('视觉、语音和信号处理中心', 'Centre for Vision, Speech and Signal Processing', 37, 'CVSSP', '专注于计算机视觉和信号处理的研究中心', '成立于1990年代，在人工智能和机器学习方面享有国际声誉', 18, 'Prof. Andrew Davis', 60, 700, 'https://www.surrey.ac.uk/cvssp', '/images/schools/surrey-cvssp.jpg', '计算机视觉,信号处理,人工智能', '机器学习,图像处理,语音识别', 'cvssp@surrey.ac.uk', '+44 1483 686818', NOW(), NOW(), 0, 1),
('计算机科学系', 'Department of Computer Science', 37, 'DCS', '在计算机科学和信息技术方面提供专业教育', '成立于1970年代，在人工智能和网络安全方面领先', 19, 'Prof. Helen Thompson', 85, 1500, 'https://www.surrey.ac.uk/computer-science', '/images/schools/surrey-cs.jpg', '计算机科学,人工智能,网络安全', '机器学习,数据科学,信息安全', 'cs@surrey.ac.uk', '+44 1483 686819', NOW(), NOW(), 0, 1),
('音乐与传媒系', 'Department of Music and Media', 37, 'DMM', '在音乐和媒体艺术方面提供专业教育', '成立于1970年代，在音乐技术和媒体制作方面享有声誉', 20, 'Prof. Robert Anderson', 50, 800, 'https://www.surrey.ac.uk/music', '/images/schools/surrey-music.jpg', '音乐,媒体艺术,音乐技术', '音乐制作,数字媒体,声音设计', 'music@surrey.ac.uk', '+44 1483 686820', NOW(), NOW(), 0, 1);

-- 哈德斯菲尔德大学 (ID: 48) 学院数据
INSERT INTO school_faculties (
    name, english_name, school_id, code, description, history, ranking,
    dean_name, faculty_count, student_count, website, image_url,
    featured_programs, research_areas, contact_email, contact_phone,
    created_time, updated_time, is_deleted, status
) VALUES 
('人文与健康科学学院', 'School of Human and Health Sciences', 48, 'SHHS', '在人文学科和健康科学方面提供综合性教育', '成立于1960年代，在健康科学和社会工作方面享有声誉', 1, 'Prof. Sarah Johnson', 120, 2500, 'https://www.hud.ac.uk/human-health', '/images/schools/huddersfield-human-health.jpg', '健康科学,社会工作,心理学', '公共卫生,社会政策,心理健康', 'humanhealth@hud.ac.uk', '+44 1484 422288', NOW(), NOW(), 0, 1),
('商业、教育与法学学院', 'School of Business, Education and Law', 48, 'SBEL', '在商业、教育和法学方面提供专业教育', '建立于1960年代，在商业教育和法律培训方面享有声誉', 2, 'Prof. Michael Brown', 150, 3000, 'https://www.hud.ac.uk/business-education-law', '/images/schools/huddersfield-business.jpg', '商业管理,教育学,法学', '商业创新,教育研究,法律实务', 'business@hud.ac.uk', '+44 1484 422289', NOW(), NOW(), 0, 1),
('商学院', 'Business School', 48, 'BS', '提供全面的商业教育和管理培训', '成立于1970年代，在工商管理和国际商务方面领先', 3, 'Prof. David Wilson', 100, 2000, 'https://www.hud.ac.uk/business-school', '/images/schools/huddersfield-business-school.jpg', '工商管理,国际商务,金融学', '商业战略,创业管理,金融创新', 'businessschool@hud.ac.uk', '+44 1484 422290', NOW(), NOW(), 0, 1),
('应用科学学院', 'School of Applied Sciences', 48, 'SAS', '在应用科学和技术方面提供专业教育', '建立于1960年代，在化学和生物科学方面享有声誉', 4, 'Prof. Lisa Anderson', 90, 1500, 'https://www.hud.ac.uk/applied-sciences', '/images/schools/huddersfield-applied-sciences.jpg', '化学,生物科学,环境科学', '应用化学,生物技术,环境监测', 'appliedsciences@hud.ac.uk', '+44 1484 422291', NOW(), NOW(), 0, 1),
('艺术与人文学院', 'School of Arts and Humanities', 48, 'SAH', '在艺术和人文学科方面提供创新教育', '历史悠久，在艺术设计和人文研究方面享有声誉', 5, 'Prof. Emma Roberts', 80, 1200, 'https://www.hud.ac.uk/arts-humanities', '/images/schools/huddersfield-arts.jpg', '艺术设计,英语文学,历史学', '当代艺术,文学研究,文化史', 'arts@hud.ac.uk', '+44 1484 422292', NOW(), NOW(), 0, 1),
('计算机与工程学院', 'School of Computing and Engineering', 48, 'SCE', '在计算机科学和工程技术方面提供专业教育', '成立于1970年代，在计算机科学和工程应用方面领先', 6, 'Prof. James Miller', 110, 1800, 'https://www.hud.ac.uk/computing-engineering', '/images/schools/huddersfield-computing.jpg', '计算机科学,工程学,信息技术', '人工智能,软件工程,工程设计', 'computing@hud.ac.uk', '+44 1484 422293', NOW(), NOW(), 0, 1);

-- 提交事务
COMMIT;